### PR TITLE
feat(add-eslint): add eslint and prettier setup command for backend and frontend

### PR DESCRIPTION
**Pull request by ZeeshanMukhtar1**
### Pull Request (PR) Description:
**Title:** `feat(add-eslint): add eslint and prettier setup command for backend and frontend`

**Description:**
This PR introduces a new `add-eslint` command to the CLI that simplifies the setup of ESLint and Prettier in both `frontend` and `backend` directories. This feature allows users to configure linting and code formatting in their MERN projects with ease.

**Changes:**
- Created `.eslintrc.json` files in each environment with appropriate configurations.
- Installed `eslint` and `prettier` as dependencies in the target directory.
- Console messages provide feedback at each setup stage for improved user experience.

**Checklist:**
- [x] Tested changes locally.
- [x] Documentation updated to reflect new command.
- [x] Code follows style guidelines.
- [x] Commit messages are clear and follow conventions.
- [x] Branch is up to date with `main`.

### CODE REVIEW

**Comment by ZeeshanMukhtar1** [comment]
Hi @manishraj27, I’ve added the add-eslint command to simplify ESLint and Prettier setup for both backend and frontend. It would be great if you could take a look and provide feedback or approval. Thank you!

**Review by manishraj27 — CHANGES_REQUESTED** [review]
It is ok that it can set up eslist for backend, frontend and both 
but i want you to implement that this function can run into any project its not necessary that the root name should be frontend.

**Comment by ZeeshanMukhtar1** [comment]
Hi @manishraj27 , I've implemented the requested changes for the ESLint setup command, make ESLint setup flexible for any project structure. Could you please review and merge when you have a moment? Thank you!

**Review by manishraj27 — CHANGES_REQUESTED** [review]
What are the updated commands now?

**Review by manishraj27 — CHANGES_REQUESTED** [review]
image
it should properly configure the file see whether it is module or not also add script to run lint in package.json

**Comment by ZeeshanMukhtar1** [comment]
Done updating readme.me

**Comment by ZeeshanMukhtar1** [comment]
Addressing Edge Cases
The current implementation covers the following edge cases:

Setting Up ESLint in Backend Only: Proper Node-specific configuration.
Setting Up ESLint in Frontend Only: Proper React-specific configuration.
Setting Up ESLint in the Root Directory: Assumes a Node environment by default, which is reasonable if the root is treated as a backend (common in many Node.js projects).

**Review by manishraj27 — COMMENTED** [review]
image
script is not adding to the package.json

**Comment by manishraj27** [comment]
image

image

ok so it will see if the command has directory as frontend then only it would create for react. can it be more optimised

**Comment by manishraj27** [comment]
Automatic Project Detection
Automatically detects project type (React, Vue, TypeScript, Node.js, or plain JavaScript)
Applies appropriate configurations based on project type

**Comment by ZeeshanMukhtar1** [comment]
Hi @manishraj27,

I’ve made several key improvements in response to your feedback:

- Automatic project type detection (React, Vue, TypeScript, Node.js)
- Project-specific ESLint configurations
- Separate frontend/backend configurations
- Enhanced error handling and validation
- Added a .eslintignore file
- Introduced a format script with Prettier
- Support for multiple file extensions
- Added a force override option
- Included a skip installation option
- Improved async/await usage
- Better console feedback
- More comprehensive Prettier configuration

You can find these changes in my latest commit: e1c910c31dca5f977de7e873ae79979906ea6f48.

Is this okay to merge now?

Thanks!

**Comment by manishraj27** [comment]
@ZeeshanMukhtar1 https://github.com/manishraj27/mern-project-cli/pull/20

**Comment by ZeeshanMukhtar1** [comment]
> @ZeeshanMukhtar1 #20

Looks good  @manishraj27

**Comment by manishraj27** [comment]
@ZeeshanMukhtar1 so i will close this pr #18  and merge #20 with main

**Comment by ZeeshanMukhtar1** [comment]
> @ZeeshanMukhtar1 so i will close this pr #18 and merge #20 with main


Hi @manishraj27,

I wanted to highlight PR #20, which builds on the improvements made in PR #18. I believe it’s important to merge this as it introduces several enhancements that significantly improve the ESLint setup functionality. 

### Key Enhancements in PR #20:
1. **Error Handling in `setupESLint`**: Provides improved feedback for each step, making it easier to identify and troubleshoot issues.
2. **Detailed Logging**: Logs paths for each configuration file created, which aids in better tracking.
3. **Extended `detectProjectType`**: Now includes support for detecting Next.js projects, enhancing versatility.
4. **Confirmation Prompt for Overwriting Configurations**: Adds a safeguard by prompting before overwriting any existing config files.

I believe these improvements significantly enhance the functionality and user experience. Could you please verify my changes in the following commits?

- [Commit 1](https://github.com/manishraj27/mern-project-cli/pull/18/commits/8d9646fd218ff0a5ffbc95ec7b245fe1a746768a)
- [Commit 2](https://github.com/manishraj27/mern-project-cli/pull/18/commits/57fdb5128b90c4741aedbadd5885167133130604)

**Comment by ZeeshanMukhtar1** [comment]
> @ZeeshanMukhtar1 so i will close this pr #18 and merge #20 with main
Hi @manishraj27,

@manishraj27  I’d like to emphasize the importance of merging PR #18, which I created, as it lays the foundation for the enhancements introduced in PR #20. 

### Key Features in PR #18:
1. **Improved Error Handling** in `setupESLint`.
2. **Detailed Logging** for configuration files.
3. **Extended Project Type Detection** for Next.js.
4. **Confirmation Prompt** for overwriting configs.

These enhancements significantly improve the ESLint setup. Please consider merging PR #18 before proceeding with #20.

Here are the relevant commits for review:
- [Commit 1](https://github.com/manishraj27/mern-project-cli/pull/18/commits/8d9646fd218ff0a5ffbc95ec7b245fe1a746768a)
- [Commit 2](https://github.com/manishraj27/mern-project-cli/pull/18/commits/57fdb5128b90c4741aedbadd5885167133130604)

**Comment by ZeeshanMukhtar1** [comment]
Closes #17

**Comment by manishraj27** [comment]
image
have you checked out the commands ?
I noticed that the browser setting is toggling to true even in a Node project. I've double-checked this several times, and the same issue keeps recurring. To address it, I've made corrections and submitted a new pull request (#20). 

Regarding the command options, I think simplifying would help us meet the primary goal of detecting the project type and setting up ESLint without adding `-f` or `-s` options, which feel somewhat redundant here. For now, I'll close PR #18  and move forward with merging #20.



    `.command('add-eslint` [directory]')
    .description('Initialize ESLint and Prettier in the specified directory')
    .option('-f, --force', 'Force installation even if configs exist')
    .option('-s, --skip-install', 'Skip dependency installation')
    `

**Review by manishraj27 — COMMENTED** [review]
Give a through check

**Pull request closed without merging**
